development: &default
  adapter: postgresql
  encoding: unicode
  database: champaign
  pool: 5
  username: <%= ENV['PG_USERNAME'] %>
  host: <%= ENV['PG_HOST'] %>

test:
  <<: *default
  database: champaign_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 10 %>

